name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build Todo.Domain
      run: |
            cd ./Todo.Domain
            dotnet restore
            dotnet build --no-restore
            cd ..
    
    - name: Build Todo.Domain.Infra
      run: |
            cd ./Todo.Domain.Infra
            dotnet restore
            dotnet build --no-restore
            cd ..

    - name: Build Todo.Domain.API
      run: |
            cd ./Todo.Domain.API
            dotnet restore
            dotnet build --no-restore
            cd ..

    - name: Test Todo.Domain.Tests
      run: |
            cd ./Todo.Domain.Tests
            dotnet restore
            dotnet test --verbosity normal
